### ISSUE TITLE
Missing Source Code

### ISSUE THREAD

**Issue by cookiengineer** [bowenbaker/metaqnn#1]
Your method of generating CNN designs seems to be pretty straight-forward. However, there's no source code of the MetaQNN available - so nobody can verify the same results and neither verify that it's actually working.

Will the source code of the MetaQNN be released in future?

**Comment by bowenbaker** [comment]
We hope to release in the future, but we are currently in the departmental process of being approved to release our codebase. However, if you are eager to verify our results, our paper (https://arxiv.org/abs/1611.02167) describes the details of the experiment.

**Comment by rigid** [comment]
code or it didn't happen!
;)
Are there any news regarding the departmental approval? A release would be highly appreciated.

**Comment by irwenqiang** [comment]
I'm looking forward to the release of source code, too :)

**Comment by irwenqiang** [comment]
The [paper decisions of ICLR 2017 ](https://openreview.net/forum?id=S1c2cvqee)have been published.    
I'm still interested in your method to automatic design of neural network architectures.  
Could you open the source code? @bowenbaker   
Thanks very much!

**Comment by bowenbaker** [comment]
Hey guys, sorry for the super long time to get this opensourced. I just pushed the base version of the code with everything you should need to run experiments from our paper. Please let me know if you have any questions on anything! Also please checkout the paper we arXiv'd recently https://arxiv.org/abs/1705.10823 if you want to speed up the architecture selection process.
