### ISSUE TITLE
When I run python caffe_client.py cifar10 unique_client_identifier server_ip_addr -gpu 4？ I find an error

### ISSUE THREAD

**Issue by MinggangZhao** [bowenbaker/metaqnn#3]
When I run python caffe_client.py cifar10 unique_client_identifier server_ip_addr -gpu 4 

There is an error:  Connection failed - goodbye!  

Why this error happened？

**Comment by bowenbaker** [comment]
Make sure you have the q_server running. Try running the q_server and the client on the same machine to ensure that it is not a connection issue on your end.

Let me know if you have further issues!

**Comment by MinggangZhao** [comment]
Thank you very much!  I have solved this problem.
